#!/usr/bin/env bash

# for custom llvm build option
cmake -Wno-dev -G Ninja -DLLVM_INCLUDE_BENCHMARKS=OFF -DCMAKE_INSTALL_PREFIX=$PREFIX -DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_LINK_LLVM_DYLIB=ON -DLLVM_ENABLE_RTTI=ON $SRCTREE

ninja -18
