name: Compiler Bootstrap CI

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache and Restore Haskell Dependency
      uses: actions/cache@v3
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-global-

#     - name: Cache LLVM ToolSet
#       id: cache-llvm
#       uses: actions/cache@v3
#       with:
#         path: |
#           ./llvm
#         key: llvm-9
#         restore-keys: llvm-9

    - name: Setup Haskell Stack
      uses: haskell/actions/setup@v2
      with:
        stack-setup-ghc: true
        enable-stack: true
        stack-version: 'latest'
        cabal-version: '3.4.0.0'

#     - name: LLVM Environment
#       uses: KyleMayes/install-llvm-action@v1
#       with:
#         version: "9.0"
#         cached: ${{ steps.cache-llvm.outputs.cache-hit }}

    - name: LLVM Environment
      run: |
        curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-15 main"
        sudo apt-get update
        sudo apt-get -y install llvm-15-dev
      shell: bash

    - name: Cache and Restore Local builds
      uses: actions/cache@v3
      with:
        path: bootstrap/.stack-work
        key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('**/*.hs') }}
        restore-keys: |
          ${{ runner.os }}-stack-work-

    - name: Test llvm toolset
      run: |
        echo -n "llvm-config version:"
        echo `llvm-config --version`
        echo -n "available link flags: "
        echo `llvm-config --link-shared --libs all`
    - name: Build
      run: |
        cd bootstrap
        echo "allow-newer: true" > ~/.stack/config.yaml # FIXME: rebuild project dependency
        stack build
