name: Compiler Bootstrap CI

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Haskell Stack
      uses: haskell/actions/setup@v2
      with:
        stack-setup-ghc: true
        enable-stack: true
        stack-version: 'latest'

    - name: Cache LLVM ToolSet
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: |
          ./llvm
        key: llvm-9

    - name: LLVM Environment
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "9.0"
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}

    - name: Cache Haskell Dependency
      uses: actions/cache@v3
      env:
        cache-name: cache-haskell
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Build
      run: |
        cd bootstrap
        stack build
